# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "fluent-plugin-solr"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nobutaka Nakazawa"]
  s.bindir = "/etc/fluent/plugin"
  s.date = "2011-11-18"
  s.description = "Solr output plugin for Fluent event collector"
  s.email = "nakazawa.nobutaka@brains-tech.co.jp"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/fluent/plugin/out_solr.rb"
  ]
  s.homepage = "http://github.com/btigit/fluent-plugin-solr"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Solr output plugin for Fluent event collector"

  deps = {
    :development => {
        'bundler' => "~> 1.3.0",
        'jeweler' => "~> 1.6.4"
    },
    :runtime => {
        'fluentd' => "~> 0.10.39",
        'rsolr'   => "~> 1.0.9"
    }

  }

  s.specification_version = 3 if s.respond_to?(:specification_version)

  if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    deps.each_pair do |deps_type, gem_list|
      gem_list.each_pair do |gem_name, version|
        s.send(:"add_#{deps_type}_dependency", gem_name, [version])
      end
    end
  else
    deps.each_pair do |_, gem_list|
      gem_list.each_pair do |gem_name, version|
        s.add_dependency gem_name, [version]
      end
    end
  end

end

